test_that("MV8-H exact500 remaining closure is complete and firewalled", {
  audit <- file.path("..", "..", "docs", "audits", "mv08h-exact500-remaining-v2")
  expect_true(file.exists(file.path(audit, "MV08H_EXACT500_REMAINING_CLOSURE_2026-08-20.md")))
  report <- paste(readLines(file.path(audit, "MV08H_EXACT500_REMAINING_CLOSURE_2026-08-20.md"), warn = FALSE), collapse = "\n")
  expect_match(report, "68/68")
  expect_match(report, "exact-500")
  expect_match(report, "common475")
  expect_match(report, "33,563")
  expect_match(report, "384")
  expect_match(report, "Firewalls")

  validation <- read.csv(file.path(audit, "mv08h-exact500-unit-validation.csv"), check.names = FALSE, stringsAsFactors = FALSE)
  summary <- read.csv(file.path(audit, "mv08h-exact500-unit-summary.csv"), check.names = FALSE, stringsAsFactors = FALSE)
  binding <- read.csv(file.path(audit, "mv08h-exact500-remaining-input-binding.csv"), check.names = FALSE, stringsAsFactors = FALSE)
  execution <- read.csv(file.path(audit, "mv08h-exact500-remaining-execution-evidence.csv"), check.names = FALSE, stringsAsFactors = FALSE)
  manifest <- read.csv(file.path(audit, "mv08h-exact500-remaining-artifact-manifest.csv"), check.names = FALSE, stringsAsFactors = FALSE)

  expect_equal(nrow(validation), 68L)
  expect_true(all(validation$passed %in% c(TRUE, "TRUE", "True")))
  expect_equal(nrow(summary), 7L)
  expect_true(all(summary$exact500_present == 500L))
  expect_true(all(summary$common475_present == 475L))
  expect_equal(nrow(binding), 7L)
  expect_true(all(binding$input_binding_passed %in% c(TRUE, "TRUE", "True")))
  expect_equal(nrow(execution), 7L)
  expect_true(all(execution$success_marker_present %in% c(TRUE, "TRUE", "True")))
  expect_true(all(execution$stderr_empty %in% c(TRUE, "TRUE", "True")))
  expect_true(all(execution$resource_gates_passed %in% c(TRUE, "TRUE", "True")))
  expect_true(all(execution$private_outputs_published %in% c(FALSE, "FALSE", "False")))
  expect_true(all(grepl("terminal-perf", execution$resource_evidence_source, fixed = TRUE)))
  expect_true(all(manifest$public_release_permitted %in% c(TRUE, "TRUE", "True")))
  expect_true(all(manifest$contains_private_matrix_or_barcode_data %in% c(FALSE, "FALSE", "False")))
  expect_true(all(vapply(seq_len(nrow(manifest)), function(i) {
    identical(toupper(digest::digest(file = file.path(audit, manifest$artifact[[i]]), algo = "sha256", serialize = FALSE)), toupper(manifest$sha256[[i]]))
  }, logical(1))))
})
