test_that("MV17-D prefreeze is synthetic-only and exact-head bound", {
  root <- testthat::test_path("..","..")
  audit <- file.path(root,"docs","audits","mv17d-localization-prefreeze-v1")
  skip_if_not(dir.exists(audit),"MV17-D prefreeze not built")
  readc <- function(name) read.csv(file.path(audit,name),stringsAsFactors=FALSE,check.names=FALSE)
  contract <- readc("mv17d-contract.csv"); gates <- readc("mv17d-validation.csv")
  decision <- readc("mv17d-decision.csv"); manifest <- readc("mv17d-artifact-manifest.csv")
  expect_equal(nrow(gates),13L); expect_true(all(gates$passed))
  expect_equal(contract$coefficient_field,2L)
  expect_equal(length(strsplit(contract$H1_methods,";",fixed=TRUE)[[1]]),2L)
  expect_true(contract$row_order_invariance_required)
  expect_false(contract$real_localization_authorized)
  expect_true(decision$synthetic_execution_authorized_after_commit)
  files <- file.path(audit,manifest$artifact)
  expect_equal(as.numeric(file.info(files)$size),manifest$bytes)
  hashes <- vapply(files,digest::digest,character(1L),algo="sha256",file=TRUE,serialize=FALSE)
  expect_equal(unname(hashes),unname(manifest$sha256))
})
