test_that("MV17-G controller-interruption recovery implementation parses", {
  root <- testthat::test_path("..", "..")
  scripts <- file.path(root, "scripts", c(
    "build_mv17g_controller_interruption_recovery_prefreeze.R",
    "quarantine_mv17g_interrupted_wave.R",
    "run_mv17g_calibration_parallel_recovery.R",
    "build_mv17g_parallel_calibration_closure.R"
  ))
  expect_true(all(file.exists(scripts)))
  for (path in scripts) expect_silent(parse(path))
  recovery <- paste(readLines(scripts[[1]], warn = FALSE), collapse = "\n")
  quarantine <- paste(readLines(scripts[[2]], warn = FALSE), collapse = "\n")
  runner <- paste(readLines(scripts[[3]], warn = FALSE), collapse = "\n")
  expect_match(recovery, "artifact_prefix != 794L", fixed = TRUE)
  expect_match(recovery, "admitted_prefix != 786L", fixed = TRUE)
  expect_match(recovery, "manual_replay_exception_children", fixed = TRUE)
  expect_match(quarantine, "787:794", fixed = TRUE)
  expect_match(quarantine, "rollback", fixed = TRUE)
  expect_match(runner, "pending <- scan$job_order[scan$state == \"absent\"]", fixed = TRUE)
})

test_that("MV17-G controller-interruption recovery prefreeze is exact and aggregate-only", {
  root <- testthat::test_path("..", "..")
  audit <- file.path(root, "docs", "audits", "mv17g-controller-interruption-recovery-prefreeze-v2")
  skip_if_not(dir.exists(audit), "MV17-G controller-interruption recovery prefreeze absent")
  read <- function(name) read.csv(file.path(audit, name), stringsAsFactors = FALSE, check.names = FALSE)
  validation <- read("mv17g-controller-recovery-validation.csv")
  contract <- read("mv17g-controller-recovery-contract.csv")
  state <- read("mv17g-controller-recovery-state-summary.csv")
  decision <- read("mv17g-controller-recovery-decision.csv")
  manifest <- read("mv17g-controller-recovery-artifact-manifest.csv")
  expect_equal(nrow(validation), 40L)
  expect_true(all(validation$passed))
  expect_equal(contract$artifact_present_prefix_children, 794L)
  expect_equal(contract$resource_admitted_prefix_children, 786L)
  expect_equal(contract$manual_replay_exception_children, 8L)
  expect_equal(contract$runner_restart_job_order, 787L)
  expect_equal(contract$resume_after_replayed_wave_job_order, 795L)
  expect_equal(contract$workers, 8L)
  expect_equal(contract$threads_per_child, 1L)
  expect_equal(contract$automatic_retries, 0L)
  expect_true(contract$owner_authorization_recorded)
  expect_true(contract$interrupted_wave_quarantine_required)
  expect_equal(state$controller_processes, 0L)
  expect_equal(state$attempt1_GNU_time_bytes, 0)
  expect_equal(state$receipt_complete_wave_children, 3L)
  expect_equal(state$receipt_incomplete_wave_children, 5L)
  expect_equal(decision$manual_replay_exception_children, 8L)
  expect_equal(decision$automatic_retries, 0L)
  expect_false(decision$scientific_estimand_changed)
  expect_false(any(c("unit_id", "unit_order", "source_path", "artifact") %in% names(state)))
  files <- file.path(audit, manifest$artifact)
  expect_equal(as.numeric(file.info(files)$size), manifest$bytes)
  expect_equal(
    unname(vapply(files, digest::digest, character(1L), algo = "sha256", file = TRUE, serialize = FALSE)),
    unname(manifest$sha256)
  )
})
