test_that("MV8-H topology panel seed gate preserves the exact-500 block", {
  path <- file.path("..", "..", "docs", "audits", "mv08h-topology-panel-seed-gate-v1", "mv08h-topology-panel-seed-gate.csv")
  skip_if_not(file.exists(path))
  gate <- read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)
  expect_equal(nrow(gate), 5L)
  expect_equal(gate$seed, 20260805:20260809)
  expect_equal(gate$selected_cells, rep(384L, 5L))
  expect_equal(gate$panel_genes, rep(500L, 5L))
  expect_true(all(gate$retained_panel_genes < 500L))
  expect_true(all(!gate$panel_retention_pass))
  expect_true(all(gate$labels_outcomes_opened == FALSE))
  expect_true(all(gate$landscapes_computed == FALSE))
  expect_false(any(tolower(names(gate)) %in% c("label", "outcome", "barcode", "expression")))
})

test_that("MV8-H topology prefreeze binds separate views and corrected landscapes", {
  path <- file.path("..", "..", "docs", "audits", "mv08h-topology-review-prefreeze-v1", "mv08h-topology-review-contract.csv")
  skip_if_not(file.exists(path))
  contract <- read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)
  expect_equal(contract$cell_view, "cell_topology_v1")
  expect_equal(contract$gene_view, "gene_topology_v1")
  expect_equal(contract$homology, "H0_and_H1_separate")
  expect_match(contract$landscape_definition, "all_active")
  expect_match(contract$landscape_definition, "no_fixed_cap_or_grid")
  expect_false(contract$labels_outcomes_opened)
  expect_false(contract$remaining_units_opened)
})
