test_that("MV10-S freezes complete outcome review before opening values", {
  root <- testthat::test_path("..", "..")
  audit <- file.path(root, "docs", "audits",
                     "mv10s-outcome-review-prefreeze-v1")
  read_audit <- function(name) read.csv(
    file.path(audit, name), stringsAsFactors = FALSE, check.names = FALSE
  )
  manifest <- read_audit("mv10s-artifact-manifest.csv")
  files <- file.path(audit, manifest$artifact)
  expect_true(all(file.exists(files)))
  expect_equal(as.numeric(file.info(files)$size), as.numeric(manifest$bytes))
  expect_equal(unname(vapply(files, function(file) digest::digest(
    file = file, algo = "sha256", serialize = FALSE
  ), character(1L))), manifest$sha256)
  contract <- read_audit("mv10s-contract.csv")
  schemas <- read_audit("mv10s-source-schema.csv")
  aggregation <- read_audit("mv10s-aggregation-contract.csv")
  figures <- read_audit("mv10s-figure-contract.csv")
  review <- read_audit("mv10s-review-contract.csv")
  implementation <- read_audit("mv10s-implementation-bindings.csv")
  sources <- read_audit("mv10s-source-freeze.csv")
  decision <- read_audit("mv10s-decision.csv")
  validation <- read_audit("mv10s-validation.csv")

  expect_equal(contract$execution_head,
               "5e120da79be9fb04b3955831d5180bb8a2f6d224")
  expect_equal(contract$source_seed_rows, 1500L)
  expect_equal(contract$source_summary_rows, 300L)
  expect_equal(contract$representations, 3L)
  expect_equal(contract$homology_dimensions, 2L)
  expect_equal(contract$methods, 5L)
  expect_equal(contract$estimable_endpoints, 5L)
  expect_equal(contract$structural_nonendpoints, 1L)
  expect_equal(contract$metrics, 2L)
  expect_equal(contract$figures, 6L)
  expect_false(contract$source_values_opened_before_table_and_figure_freeze)
  expect_false(contract$p_values)
  expect_false(contract$method_selection)
  expect_false(contract$ranking)
  expect_false(contract$H0_H1_combined)
  expect_false(contract$biological_claims)
  expect_false(contract$manuscript_claims)
  expect_identical(schemas$source_id,
                   c("seed_metrics", "unit_summaries", "structural_status"))
  expect_identical(schemas$expected_rows, c(1500L, 300L, 1L))
  expect_true(all(!schemas$scientific_values_opened_during_prefreeze))
  expect_identical(aggregation$expected_rows, c(300L, 60L, 6L))
  expect_true(all(!aggregation$result_dependent_filter))
  expect_true(all(!aggregation$ranking))
  expect_equal(nrow(figures), 6L)
  expect_true(all(figures$format == "png"))
  expect_true(all(figures$all_three_representations))
  expect_true(all(figures$H0_H1_separate))
  expect_true(all(figures$both_metrics))
  expect_true(all(figures$seed_range))
  expect_true(all(!figures$ranking))
  expect_equal(nrow(review), 12L)
  expect_equal(nrow(implementation), 7L)
  expect_true(all(file.exists(file.path(root, implementation$file))))
  expect_true(all(grepl("^[0-9a-f]{64}$", implementation$sha256)))
  source_files <- ifelse(
    grepl("^(/|[A-Za-z]:[/\\\\])", sources$artifact),
    sources$artifact, file.path(root, sources$artifact)
  )
  expect_true(all(file.exists(source_files)))
  expect_equal(unname(vapply(source_files, function(file) digest::digest(
    file = file, algo = "sha256", serialize = FALSE
  ), character(1L))), sources$sha256)
  expect_equal(nrow(validation), 36L)
  expect_true(all(validation$passed))
  expect_true(decision$synthesis_authorized_after_commit)
  expect_false(decision$figure_render_authorized)
  expect_false(decision$scientific_interpretation_authorized)
  expect_false(decision$method_selection_authorized)
  expect_false(decision$biological_claims_authorized)
  expect_false(decision$manuscript_claims_authorized)
})
