test_that("MV8-I public common475 validation is complete and firewalled", {
  audit <- file.path("..", "..", "docs", "audits", "mv08i-hca-validation-v1")
  expect_true(file.exists(file.path(audit, "mv08i-independent-validation.csv")))
  topology <- read.csv(file.path(audit, "mv08i-topology-summary.csv"), check.names = FALSE)
  execution <- read.csv(file.path(audit, "mv08i-landscape-execution.csv"), check.names = FALSE)
  levels <- read.csv(file.path(audit, "mv08i-landscape-level-summary.csv"), check.names = FALSE)
  ledger <- read.csv(file.path(audit, "mv08i-repeat-ledger.csv"), check.names = FALSE)
  expect_equal(nrow(topology), 32L)
  expect_equal(length(unique(topology$unit_id)), 8L)
  expect_true(all(topology$point_count[topology$view_id == "cell_topology_v1"] == 384L))
  expect_true(all(topology$point_count[topology$view_id == "gene_topology_v1"] == 475L))
  expect_true(all(!topology$labels_outcomes_opened & !topology$landscapes_computed & !topology$fusion_computed))
  expect_equal(nrow(execution), 32L)
  expect_true(all(execution$integration_method == "exact_critical_breakpoint_v1"))
  expect_true(all(execution$level_policy == "all_active_consecutive_levels" & execution$grid_policy == "none"))
  expect_equal(nrow(levels), sum(execution$active_level_count))
  expect_true(all(ledger$byte_identical))
  expect_true(all(ledger$primary_sha256 == ledger$repeat_sha256))
})
