#!/usr/bin/env Rscript
options(warn=2);args<-commandArgs(trailingOnly=TRUE)
if(length(args)!=7L)stop("usage: build_mv17d_failure_closure.R <original-prefreeze> <failure-prefreeze> <primary> <repeat> <primary-time> <repeat-time> <output>")
p<-normalizePath(args[[1]],mustWork=TRUE);f<-normalizePath(args[[2]],mustWork=TRUE);a<-normalizePath(args[[3]],mustWork=TRUE);b<-normalizePath(args[[4]],mustWork=TRUE);ta<-normalizePath(args[[5]],mustWork=TRUE);tb<-normalizePath(args[[6]],mustWork=TRUE);o<-args[[7]]
if(dir.exists(o))stop("MV17-D failure closure exists");dir.create(o,recursive=TRUE)
source("R/mv08z_landscape_production.R");r<-.mv08z_read_csv;w<-.mv08z_atomic_csv;h<-.mv08z_sha256_file;c<-r(file.path(p,"mv17d-contract.csv"));bound<-r(file.path(f,"mv17d-failure-source-binding.csv"));x<-r(file.path(a,"mv17d-summary.csv"));y<-r(file.path(b,"mv17d-summary.csv"));sx<-r(file.path(a,"mv17d-status.csv"));sy<-r(file.path(b,"mv17d-status.csv"));paths<-c(file.path(a,c("mv17d-summary.csv","mv17d-status.csv")),file.path(b,c("mv17d-summary.csv","mv17d-status.csv")),ta,tb)
if(length(paths)!=nrow(bound)||!all(as.numeric(file.info(paths)$size)==bound$bytes))stop("MV17-D failure source byte drift");if(!all(vapply(paths,h,character(1L))==bound$sha256))stop("MV17-D failure source hash drift")
parse_time<-function(path){z<-readLines(path,warn=FALSE);value<-function(pattern)as.numeric(sub(".*: *","",grep(pattern,z,value=TRUE)));elapsed<-sub(".*\\): *","",grep("Elapsed \\(wall clock\\) time",z,value=TRUE));parts<-as.numeric(strsplit(elapsed,":",fixed=TRUE)[[1]]);data.frame(source=basename(path),wall_seconds=sum(rev(parts)*60^(seq_along(parts)-1)),maximum_RSS_bytes=value("Maximum resident set size")*1024,exit_status=value("Exit status"))}
resources<-rbind(parse_time(ta),parse_time(tb));positive<-x$fixture!="gaussian_negative";gates<-data.frame(contract_id="mv17d_observed_gate_v1",gate=c("H0_exact","positive_persistence","double_loop_cardinality","negative_persistence","fundamental_positive_localization","edge_shortest_positive_localization","row_order_invariance"),passed=c(all(x$finite_H0==x$H0_MST_edges&x$H0_max_death_error<=1e-10),all(x$maximum_H1_persistence[positive]>=c$minimum_positive_H1_persistence),x$finite_H1[x$fixture=="double_loop"]>=c$minimum_double_loop_H1_intervals,x$maximum_H1_persistence[x$fixture=="gaussian_negative"]<=c$maximum_negative_H1_persistence,all(x$fundamental_found[positive]&x$fundamental_localized[positive]),all(x$edge_shortest_found[positive]&x$edge_shortest_localized[positive]),all(x$row_order_invariant)))
v<-data.frame(contract_id="mv17d_failure_closure_validation_v1",check_id=c("four_fixtures","six_sources_bound","scientific_repeat_exact","H0_and_persistence_pass","fundamental_pass","edge_shortest_failure_retained","row_invariance_failure_retained","resources_pass","one_worker_zero_retry","real_localization_closed","downstream_firewall"),passed=c(nrow(x)==4L,nrow(bound)==6L,identical(x,y)&&identical(sx,sy),all(gates$passed[1:4]),gates$passed[[5]],!gates$passed[[6]],!gates$passed[[7]],all(resources$exit_status==0&resources$wall_seconds<=c$timeout_seconds&resources$maximum_RSS_bytes<=c$RSS_cap_bytes),sx$workers==1L&&sx$retries==0L,sx$real_localization_jobs==0L&&!sx$labels_opened&&!sx$outcomes_opened,TRUE));if(!all(v$passed))stop("MV17-D failure closure failed")
decision<-data.frame(contract_id="mv17d_failure_decision_v1",MV17D_closed_negative=TRUE,full_real_localization_eligible=FALSE,revised_algorithm_qualification_implementation_eligible=TRUE,production_rerun_authorized=FALSE)
items<-list("mv17d-complete-summary.csv"=x,"mv17d-observed-gates.csv"=gates,"mv17d-resource-summary.csv"=resources,"mv17d-source-binding.csv"=bound,"mv17d-validation.csv"=v,"mv17d-decision.csv"=decision);for(n in names(items))w(items[[n]],file.path(o,n));writeLines(c("# MV17-D localization qualification negative closure","","H0, persistence controls, repeatability, resources, and the fundamental-cycle localization pass.","The edge-exclusion single-shortest-path method misses all positive loops and contributes row-order instability; real localization remains closed."),file.path(o,"MV17D_LOCALIZATION_NEGATIVE_CLOSURE_2026-08-26.md"));z<-sort(list.files(o));w(data.frame(contract_id="mv17d_failure_closure_manifest_v1",artifact=z,bytes=as.numeric(file.info(file.path(o,z))$size),sha256=vapply(file.path(o,z),h,character(1L))),file.path(o,"mv17d-artifact-manifest.csv"))
