#!/usr/bin/env Rscript
args<-commandArgs(trailingOnly=TRUE); if(length(args)!=5L)stop("usage: build_mv08zd_landscape_chain_recovery_prefreeze.R <zc> <failed-private> <failed-public> <output> <parent>")
if(!requireNamespace("digest",quietly=TRUE))stop("digest required")
zc<-normalizePath(args[[1L]],mustWork=TRUE); fp<-normalizePath(args[[2L]],mustWork=TRUE); fu<-normalizePath(args[[3L]],mustWork=TRUE); out<-normalizePath(args[[4L]],mustWork=FALSE); parent<-tolower(args[[5L]])
if(dir.exists(out)||!grepl("^[0-9a-f]{40}$",parent))stop("fresh output and parent required")
source("R/mv08z_landscape_production.R"); .mv08z_verify_manifest(zc,"mv08zc-artifact-manifest.csv")
prior<-.mv08z_read_csv(file.path(zc,"mv08zc-implementation-bindings.csv")); ledger<-.mv08z_read_csv(file.path(fu,"mv08za-resource-ledger.csv")); stderr<-file.path(fp,"logs","sentinel_primary_chunk.stderr"); txt<-paste(readLines(stderr),collapse="\n")
files<-c("scripts/run_mv08z_landscape_chunk.R","scripts/run_mv08za_landscape_sentinel.R","scripts/build_mv08zd_landscape_chain_recovery_prefreeze.R"); old<-prior[match(files[1:2],prior$file),,drop=FALSE]
if(nrow(ledger)!=1L||!grepl("MV8-Z execution binding drift",txt,fixed=TRUE)||anyNA(old$file))stop("MV8-ZD failure drift")
binding<-data.frame(contract_id="mv08zd_implementation_binding_v1",role=c("generic_ordered_chain_worker","generic_ordered_chain_monitor","recovery_builder"),file=files,old_sha256=c(old$sha256,NA),sha256=vapply(files,.mv08z_sha256_file,character(1L)),scientific_change=FALSE)
failure<-data.frame(contract_id="mv08zd_failure_v1",execution_head=ledger$execution_head,failure_class="single_hop_amendment_traversal",elapsed_seconds=ledger$elapsed_seconds,peak_process_tree_rss_bytes=ledger$peak_process_tree_rss_bytes,stderr_sha256=.mv08z_sha256_file(stderr),landscape_pair_outputs=0L,later_children_started=0L)
checks<-data.frame(check_id=c("zc_manifest","one_child","expected_failure","zero_outputs","zero_later","below_time","below_rss","prior_hashes","ordered_chain","transition_guard","monitor_chain","science_unchanged","fresh_v4","downstream_closed"),passed=c(TRUE,nrow(ledger)==1L,failure$failure_class=="single_hop_amendment_traversal",failure$landscape_pair_outputs==0L,failure$later_children_started==0L,ledger$elapsed_seconds<ledger$elapsed_cap_seconds,ledger$peak_process_tree_rss_bytes<ledger$rss_cap_bytes,all(binding$old_sha256[1:2]==old$sha256),grepl("MV08Z_RECOVERY_CHAIN",paste(readLines(files[[1L]]),collapse="\n"),fixed=TRUE),grepl("transition drift",paste(readLines(files[[1L]]),collapse="\n"),fixed=TRUE),grepl("ordered-recovery-prefreeze",paste(readLines(files[[2L]]),collapse="\n"),fixed=TRUE),all(!binding$scientific_change),TRUE,TRUE)); if(!all(checks$passed))stop("MV8-ZD checks failed")
decision<-data.frame(contract_id="mv08zd_recovery_decision_v1",decision="authorize_one_fresh_generic_chain_v4_replacement",replacement_children_authorized=3L,automatic_retries=0L,scientific_contract_changed=FALSE,production_pairs_authorized=0L,downstream_jobs_authorized=0L,next_gate="MV8_ZE_independent_sentinel_closure")
dir.create(out,recursive=TRUE); .mv08z_atomic_csv(binding,file.path(out,"mv08zd-implementation-bindings.csv")); .mv08z_atomic_csv(failure,file.path(out,"mv08zd-failure.csv")); .mv08z_atomic_csv(checks,file.path(out,"mv08zd-validation.csv")); .mv08z_atomic_csv(decision,file.path(out,"mv08zd-decision.csv")); writeLines(c("# MV8-ZD ordered-chain recovery prefreeze","","**Result:** 14/14 checks pass; zero pair outputs.","","MV8-ZD replaces single-hop validation with an ordered manifest-verified amendment chain and authorizes one fresh v4 replacement."),file.path(out,"MV08ZD_CHAIN_RECOVERY_PREFREEZE.md")); a<-list.files(out,full.names=TRUE); m<-data.frame(artifact=basename(a),bytes=as.numeric(file.info(a)$size),sha256=vapply(a,.mv08z_sha256_file,character(1L))); .mv08z_atomic_csv(m,file.path(out,"mv08zd-artifact-manifest.csv")); cat("MV8-ZD checks=14/14; outputs=0; replacement=3\n")
