#!/usr/bin/env Rscript
options(warn=2);args<-commandArgs(trailingOnly=TRUE);if(length(args)!=1L)stop("usage: build_mv17d_localization_prefreeze.R <output>");o<-args[[1]];if(dir.exists(o))stop("MV17-D prefreeze exists");dir.create(o,recursive=TRUE)
source("R/mv08z_landscape_production.R");h<-.mv08z_sha256_file;w<-.mv08z_atomic_csv;head<-tolower(trimws(Sys.getenv("MV17D_PREFREEZE_HEAD",unset="")));if(!grepl("^[0-9a-f]{40}$",head))stop("MV17D_PREFREEZE_HEAD required")
fixtures<-data.frame(contract_id="mv17d_fixture_v1",fixture=c("circle","noisy_circle","double_loop","gaussian_negative"),points=c(32L,32L,40L,32L),seed=c(NA,17201L,NA,17202L),expected_H1=c("positive","positive","at_least_two","negative"),stringsAsFactors=FALSE)
impls<-c("R/mv17_localization.R","scripts/build_mv17d_localization_prefreeze.R","scripts/run_mv17d_localization_qualification.R","scripts/build_mv17d_localization_closure.R","tests/testthat/test-mv17d-localization.R","tests/testthat/test-mv17d-localization-prefreeze.R");impl<-data.frame(contract_id="mv17d_implementation_binding_v1",file=impls,bytes=as.numeric(file.info(impls)$size),sha256=vapply(impls,h,character(1L)))
c<-data.frame(contract_id="mv17d_localization_prefreeze_v1",execution_head=head,H0_method="deterministic_kruskal_MST",H1_methods="nonboundary_fundamental_cycle;nonboundary_edge_exclusion_shortest_hop_cycle",coefficient_field=2L,H1_scale="midpoint_of_longest_finite_H1_interval",minimum_positive_H1_persistence=0.20,maximum_negative_H1_persistence=0.50,minimum_double_loop_H1_intervals=2L,minimum_angular_octants=4L,maximum_radial_rmse=0.15,double_loop_center_offset=1.10,tie_policy="distance_then_canonical_endpoint_tokens",canonicalization="sorted_private_point_token_support_SHA256",row_order_invariance_required=TRUE,exact_repeat_required=TRUE,one_worker=TRUE,timeout_seconds=1800L,RSS_cap_bytes=4294967296,real_localization_authorized=FALSE,labels_authorized=FALSE,outcomes_authorized=FALSE,clustering_authorized=FALSE,fusion_authorized=FALSE,biology_authorized=FALSE,manuscript_claims_authorized=FALSE)
v<-data.frame(contract_id="mv17d_validation_v1",check_id=c("four_fixtures","H0_method","two_H1_methods","field_and_scale","fixed_persistence_thresholds","known_geometry_thresholds","tie_canonicalization","row_invariance","resource_caps","implementation_bound","real_localization_closed","downstream_firewall","zero_localization_execution"),passed=c(nrow(fixtures)==4L,c$H0_method=="deterministic_kruskal_MST",length(strsplit(c$H1_methods,";",fixed=TRUE)[[1]])==2L,c$coefficient_field==2L&&grepl("midpoint",c$H1_scale),c$minimum_positive_H1_persistence==.2&&c$maximum_negative_H1_persistence==.5,c$minimum_double_loop_H1_intervals==2L&&c$minimum_angular_octants==4L&&c$maximum_radial_rmse==.15,nzchar(c$tie_policy)&&nzchar(c$canonicalization),c$row_order_invariance_required,c$one_worker&&c$RSS_cap_bytes==4294967296,all(file.exists(impls)),!c$real_localization_authorized,!any(c[c("labels_authorized","outcomes_authorized","clustering_authorized","fusion_authorized","biology_authorized","manuscript_claims_authorized")]),TRUE));if(!all(v$passed))stop("MV17-D prefreeze failed")
d<-data.frame(contract_id="mv17d_decision_v1",synthetic_execution_authorized_after_commit=TRUE,real_localization_authorized=FALSE,next_after_closure="separate_full_localization_prefreeze")
items<-list("mv17d-contract.csv"=c,"mv17d-fixtures.csv"=fixtures,"mv17d-implementation-binding.csv"=impl,"mv17d-validation.csv"=v,"mv17d-decision.csv"=d);for(n in names(items))w(items[[n]],file.path(o,n));writeLines(c("# MV17-D localization qualification prefreeze","","H0 merger edges and two H1 non-boundary cycle algorithms are frozen on four synthetic fixtures.","Real localization and all downstream scientific surfaces remain closed."),file.path(o,"MV17D_LOCALIZATION_PREFREEZE_2026-08-26.md"));f<-sort(list.files(o));w(data.frame(contract_id="mv17d_manifest_v1",artifact=f,bytes=as.numeric(file.info(file.path(o,f))$size),sha256=vapply(file.path(o,f),h,character(1L))),file.path(o,"mv17d-artifact-manifest.csv"))
