#!/usr/bin/env Rscript

options(warn = 2)
for (package in c("digest", "pkgload")) if (!requireNamespace(package, quietly=TRUE)) stop(package," required.")
pkgload::load_all(".", quiet=TRUE, export_all=TRUE)
args <- commandArgs(trailingOnly=TRUE)
if (length(args)!=7L) stop("usage: build_mv07fp_panel_prefreeze.R MV07E_DIR MV07F_DIR PRIMARY_LEDGER PRIMARY_CACHE_DIR ADDED_CACHE_DIR OUTPUT_DIR EXPECTED_HEAD")
mv07e<-args[[1]];mv07f<-args[[2]];primary_ledger_path<-normalizePath(args[[3]],winslash="/",mustWork=TRUE)
primary_cache<-normalizePath(args[[4]],winslash="/",mustWork=TRUE);added_cache<-normalizePath(args[[5]],winslash="/",mustWork=TRUE)
output<-args[[6]];expected_head<-tolower(trimws(args[[7]]));head<-tolower(trimws(system2("git",c("rev-parse","HEAD"),stdout=TRUE)))
if(!identical(head,expected_head)||!grepl("^[0-9a-f]{40}$",expected_head))stop("MV7-FP exact HEAD mismatch.")
dir.create(output,recursive=TRUE,showWarnings=FALSE);if(length(list.files(output,all.files=TRUE,no..=TRUE)))stop("Output must be empty.")
source("R/provenance_utils.R");sha<-function(p)digest::digest(file=p,algo="sha256",serialize=FALSE)
primary<-read.csv(primary_ledger_path,stringsAsFactors=FALSE,check.names=FALSE)
added<-read.csv(file.path(mv07f,"mv07f-sct-production.csv"),stringsAsFactors=FALSE,check.names=FALSE)
manifest<-mv07fp_combined_cache_manifest_v1(primary,added)
if(sha(primary_ledger_path)!="73f757a91c202a8e38dfa746fc8816f8e272caf912c33b4b959ef55102c68308")stop("Primary ledger drift.")
paths<-ifelse(manifest$source_tier=="primary90",file.path(primary_cache,manifest$private_cache_file),file.path(added_cache,manifest$private_cache_file))
actual_sha<-vapply(paths,sha,character(1));actual_bytes<-as.numeric(file.info(paths)$size)
if(any(!file.exists(paths))||any(actual_sha!=manifest$private_cache_sha256)||any(actual_bytes!=manifest$private_cache_bytes))stop("MV7-FP cache identity drift.")
v7<-read.csv(file.path(mv07f,"mv07f-independent-validation.csv"),stringsAsFactors=FALSE)
resume<-read.csv(file.path(mv07f,"mv07f-immutable-resume.csv"),stringsAsFactors=FALSE)
if(nrow(v7)!=9L||!all(.mv07fp_truth(v7$passed))||!all(.mv07fp_truth(resume[c("hashes_unchanged","bytes_unchanged","mtimes_unchanged","manifest_unchanged")])))stop("MV7-F is not closed.")
caps<-mv07fp_resource_caps_v1()
contract<-data.frame(contract_id="mv07fp_panel_prefreeze_v1",samples=124L,seeds=5L,cache_records=620L,cells_per_cache=384L,panel_size=500L,algorithm="mv06c_global_core_panel_v1",samples_per_seed=124L,transductive=TRUE,outcome_label_state="closed",panel_jobs_authorized=1L,pca_jobs_authorized=0L,ph_jobs_authorized=0L,landscape_jobs_authorized=0L,outcome_jobs_authorized=0L,stringsAsFactors=FALSE)
source_files<-c(mv07e_decision=file.path(mv07e,"mv07e-decision.csv"),mv07f_summary=file.path(mv07f,"mv07f-production-summary.csv"),mv07f_validation=file.path(mv07f,"mv07f-independent-validation.csv"),mv07f_resume=file.path(mv07f,"mv07f-immutable-resume.csv"),primary_ledger=primary_ledger_path,accepted_panel="docs/audits/mv06c-global-core-evidence/mv06c-panel.csv",selector="R/mv06_global_core_gate.R",helper="R/mv07fp_panel_lock.R",builder="scripts/build_mv07fp_panel_prefreeze.R",validator="scripts/validate_mv07fp_panel_prefreeze.R",runner="scripts/run_mv07fp_panel_lock.R",production_validator="scripts/validate_mv07fp_panel_lock.R",tests="tests/testthat/test-mv07fp-panel-lock.R",selector_tests="tests/testthat/test-mv06-global-core-gate.R",specification="docs/specifications/MV07FP_FULL124_GLOBAL_CORE_PANEL_LOCK_PREFREEZE_V1.md")
if(any(!file.exists(source_files)))stop("MV7-FP source freeze incomplete.")
locators<-unname(source_files);locators[1:4]<-c("docs/audits/mv07e-prefreeze-evidence/mv07e-decision.csv","docs/audits/mv07f-production-evidence/mv07f-production-summary.csv","docs/audits/mv07f-production-evidence/mv07f-independent-validation.csv","docs/audits/mv07f-production-evidence/mv07f-immutable-resume.csv");locators[5]<-"historical_mv05d0_sct_cache_resources_v2"
freeze<-data.frame(contract_id="mv07fp_source_freeze_v1",source_id=names(source_files),artifact_locator=locators,sha256=vapply(source_files,sha,character(1)),bytes=as.numeric(file.info(source_files)$size),accepted_head=expected_head,private_source=names(source_files)=="primary_ledger",stringsAsFactors=FALSE)
acceptance<-data.frame(contract_id="mv07fp_prefreeze_acceptance_v1",category=c("source_freeze","cache_axis","cache_hashes","mv07f_closure","resource_caps","label_firewall","panel_only"),passed=c(nrow(freeze)==15L,nrow(manifest)==620L&&length(unique(manifest$sample_id))==124L,all(actual_sha==manifest$private_cache_sha256),TRUE,nrow(caps)==1L,all(manifest$outcome_label_state=="closed"),contract$panel_jobs_authorized==1L&&sum(contract[c("pca_jobs_authorized","ph_jobs_authorized","landscape_jobs_authorized","outcome_jobs_authorized")])==0),stringsAsFactors=FALSE)
decision<-data.frame(contract_id="mv07fp_prefreeze_decision_v1",decision="authorize_one_streamed_620_cache_panel_lock",cache_records=620L,panel_size=500L,pca_authorized=FALSE,ph_authorized=FALSE,landscape_authorized=FALSE,labels_authorized=FALSE,outcomes_authorized=FALSE,next_gate="MV7-G_typed_view_PH_sentinel_prefreeze",stringsAsFactors=FALSE)
outputs<-list("mv07fp-contract.csv"=contract,"mv07fp-cache-manifest.csv"=manifest,"mv07fp-resource-caps.csv"=caps,"mv07fp-source-freeze.csv"=freeze,"mv07fp-acceptance.csv"=acceptance,"mv07fp-decision.csv"=decision)
for(n in names(outputs))write_provenance_csv(outputs[[n]],file.path(output,n))
message("MV7-FP prefreeze complete: 620 caches, panel only")
