#!/usr/bin/env Rscript
options(warn=2)
args<-commandArgs(trailingOnly=TRUE)
if(length(args)!=10L)stop("usage: build_mv17c_time_recovery_prefreeze.R <original-prefreeze> <closure-v1> <failure-record> <primary-private> <primary-public> <repeat-private> <repeat-public> <primary-time> <repeat-time> <output>",call.=FALSE)
original<-normalizePath(args[[1]],mustWork=TRUE);rejected<-normalizePath(args[[2]],mustWork=TRUE);failure_root<-normalizePath(args[[3]],mustWork=TRUE);ap<-normalizePath(args[[4]],mustWork=TRUE);au<-normalizePath(args[[5]],mustWork=TRUE);bp<-normalizePath(args[[6]],mustWork=TRUE);bu<-normalizePath(args[[7]],mustWork=TRUE);ta<-normalizePath(args[[8]],mustWork=TRUE);tb<-normalizePath(args[[9]],mustWork=TRUE);output<-args[[10]]
if(dir.exists(output))stop("MV17-C time recovery prefreeze exists",call.=FALSE)
dir.create(output,recursive=TRUE)
source("R/mv08z_landscape_production.R");source("R/mv17_calibration.R")
r<-.mv08z_read_csv;w<-.mv08z_atomic_csv;h<-.mv08z_sha256_file
head<-tolower(trimws(Sys.getenv("MV17C_TIME_RECOVERY_HEAD",unset="")));if(!grepl("^[0-9a-f]{40}$",head))stop("MV17C_TIME_RECOVERY_HEAD required",call.=FALSE)
verify<-function(root,manifest_name){m<-r(file.path(root,manifest_name));p<-file.path(root,m$artifact);if(!all(as.numeric(file.info(p)$size)==m$bytes)||!all(vapply(p,h,character(1L))==tolower(m$sha256)))stop("MV17-C recovery source manifest drift",call.=FALSE);m}
original_manifest<-verify(original,"mv17c-artifact-manifest.csv");rejected_manifest<-verify(rejected,"mv17c-artifact-manifest.csv");failure_manifest<-verify(failure_root,"mv17c-time-parser-failure-artifact-manifest.csv")
production_paths<-c(file.path(au,"mv17c-artifact-manifest.csv"),file.path(bu,"mv17c-artifact-manifest.csv"),file.path(ap,c("mv17c-scientific-metrics.csv","mv17c-private-queue.csv")),file.path(bp,c("mv17c-scientific-metrics.csv","mv17c-private-queue.csv")),ta,tb)
production<-data.frame(contract_id="mv17c_time_recovery_production_binding_v1",role=c("primary_public_manifest","repeat_public_manifest","primary_metrics","primary_queue","repeat_metrics","repeat_queue","primary_GNU_time","repeat_GNU_time"),bytes=as.numeric(file.info(production_paths)$size),sha256=vapply(production_paths,h,character(1L)))
implementation_paths<-c("R/mv17_calibration.R","scripts/build_mv17c_calibration_closure.R","scripts/build_mv17c_time_parser_failure_record.R","scripts/build_mv17c_time_recovery_prefreeze.R","tests/testthat/test-mv17c-calibration.R","tests/testthat/test-mv17c-time-recovery.R")
implementation<-data.frame(contract_id="mv17c_time_recovery_implementation_binding_v1",file=implementation_paths,bytes=as.numeric(file.info(implementation_paths)$size),sha256=vapply(implementation_paths,h,character(1L)))
rejected_binding<-data.frame(contract_id="mv17c_time_recovery_rejected_binding_v1",artifact=rejected_manifest$artifact,bytes=as.numeric(file.info(file.path(rejected,rejected_manifest$artifact))$size),sha256=vapply(file.path(rejected,rejected_manifest$artifact),h,character(1L)))
failure_binding<-data.frame(contract_id="mv17c_time_recovery_failure_binding_v1",artifact=failure_manifest$artifact,bytes=as.numeric(file.info(file.path(failure_root,failure_manifest$artifact))$size),sha256=vapply(file.path(failure_root,failure_manifest$artifact),h,character(1L)))
reported<-r(file.path(rejected,"mv17c-resource-summary.csv"));correct<-rbind(cbind(mode="primary",mv17c_parse_gnu_time_v1(ta)),cbind(mode="repeat",mv17c_parse_gnu_time_v1(tb)));reported<-reported[match(correct$mode,reported$mode),,drop=FALSE]
contract<-data.frame(contract_id="mv17c_time_recovery_contract_v1",execution_head=head,production_jobs=260L,scientific_recomputation_authorized=FALSE,production_rerun_authorized=FALSE,closure_v2_authorized_after_commit=TRUE,full_calibration_authorized=FALSE,real_localization_authorized=FALSE,labels_outcomes_clustering_fusion_claims="closed",stringsAsFactors=FALSE)
omitted_minutes<-(correct$wall_seconds-reported$outer_wall_seconds)/60
validation<-data.frame(contract_id="mv17c_time_recovery_validation_v1",check_id=c("original_prefreeze_bound","rejected_closure_bound","failure_record_bound","eight_production_sources","primary_metrics_complete","repeat_metrics_complete","corrected_minutes_recovered","outer_covers_serial_children","six_implementation_files","production_frozen","closure_v2_only","full_calibration_closed","real_localization_closed","downstream_firewall"),passed=c(nrow(original_manifest)>=1L,nrow(rejected_binding)==6L,nrow(failure_binding)==3L,nrow(production)==8L,nrow(r(file.path(ap,"mv17c-scientific-metrics.csv")))==1560L,nrow(r(file.path(bp,"mv17c-scientific-metrics.csv")))==520L,all(correct$wall_seconds>reported$outer_wall_seconds)&all(abs(omitted_minutes-round(omitted_minutes))<=1e-9),all(correct$wall_seconds>=c(sum(r(file.path(au,"mv17c-resource-ledger.csv"))$wall_seconds),sum(r(file.path(bu,"mv17c-resource-ledger.csv"))$wall_seconds))),nrow(implementation)==6L,!contract$production_rerun_authorized&& !contract$scientific_recomputation_authorized,contract$closure_v2_authorized_after_commit,!contract$full_calibration_authorized,!contract$real_localization_authorized,contract$labels_outcomes_clustering_fusion_claims=="closed"))
if(!all(validation$passed))stop("MV17-C time recovery prefreeze failed",call.=FALSE)
items<-list("mv17c-time-recovery-contract.csv"=contract,"mv17c-time-recovery-production-binding.csv"=production,"mv17c-time-recovery-implementation-binding.csv"=implementation,"mv17c-time-recovery-rejected-binding.csv"=rejected_binding,"mv17c-time-recovery-failure-binding.csv"=failure_binding,"mv17c-time-recovery-validation.csv"=validation)
for(name in names(items))w(items[[name]],file.path(output,name))
writeLines(c("# MV17-C GNU-time closure recovery prefreeze","","All 260 completed production jobs and both GNU-time receipts are frozen byte-for-byte.","Only a closure-only v2 using the corrected elapsed parser is authorized after this exact-head prefreeze commits.","No null, PH diagram, metric, empirical tail, selected unit, label, outcome, clustering, fusion, biological interpretation, or manuscript claim may be recomputed or opened."),file.path(output,"MV17C_TIME_RECOVERY_PREFREEZE_2026-08-26.md"))
files<-sort(list.files(output));w(data.frame(contract_id="mv17c_time_recovery_manifest_v1",artifact=files,bytes=as.numeric(file.info(file.path(output,files))$size),sha256=vapply(file.path(output,files),h,character(1L))),file.path(output,"mv17c-time-recovery-artifact-manifest.csv"))
message("Built MV17-C time recovery prefreeze; checks=",nrow(validation))
