#!/usr/bin/env Rscript
options(warn=2); args<-commandArgs(trailingOnly=TRUE)
if(length(args)!=5L)stop("usage: build_mv17d_failure_closure_prefreeze.R <primary> <repeat> <primary-time> <repeat-time> <output>")
a<-normalizePath(args[[1]],mustWork=TRUE);b<-normalizePath(args[[2]],mustWork=TRUE);ta<-normalizePath(args[[3]],mustWork=TRUE);tb<-normalizePath(args[[4]],mustWork=TRUE);o<-args[[5]]
if(dir.exists(o))stop("MV17-D failure prefreeze exists");dir.create(o,recursive=TRUE)
source("R/mv08z_landscape_production.R");r<-.mv08z_read_csv;w<-.mv08z_atomic_csv;h<-.mv08z_sha256_file
head<-tolower(trimws(Sys.getenv("MV17D_FAILURE_HEAD",unset="")));if(!grepl("^[0-9a-f]{40}$",head))stop("MV17D_FAILURE_HEAD required")
names<-c("mv17d-summary.csv","mv17d-status.csv");paths<-c(file.path(a,names),file.path(b,names),ta,tb);roles<-c("primary_summary","primary_status","repeat_summary","repeat_status","primary_GNU_time","repeat_GNU_time")
binding<-data.frame(contract_id="mv17d_failure_source_binding_v1",role=roles,bytes=as.numeric(file.info(paths)$size),sha256=vapply(paths,h,character(1L)))
x<-r(file.path(a,names[[1]]));y<-r(file.path(b,names[[1]]));sx<-r(file.path(a,names[[2]]));sy<-r(file.path(b,names[[2]]));positive<-x$fixture!="gaussian_negative"
impls<-c("scripts/build_mv17d_failure_closure_prefreeze.R","scripts/build_mv17d_failure_closure.R","tests/testthat/test-mv17d-failure-closure.R")
impl<-data.frame(contract_id="mv17d_failure_implementation_binding_v1",file=impls,bytes=as.numeric(file.info(impls)$size),sha256=vapply(impls,h,character(1L)))
contract<-data.frame(contract_id="mv17d_failure_closure_prefreeze_v1",execution_head=head,production_rerun_authorized=FALSE,threshold_change_authorized=FALSE,failure_closure_authorized_after_commit=TRUE,revised_algorithm_implementation_eligible_after_closure=TRUE,real_localization_authorized=FALSE,labels_authorized=FALSE,outcomes_authorized=FALSE,clustering_authorized=FALSE,fusion_authorized=FALSE,biology_authorized=FALSE,manuscript_claims_authorized=FALSE)
v<-data.frame(contract_id="mv17d_failure_prefreeze_validation_v1",check_id=c("six_sources_bound","summary_repeat_exact","status_repeat_exact","H0_and_persistence_controls_pass","fundamental_positive_localization_passes","edge_shortest_positive_gate_fails","row_invariance_gate_fails","implementation_bound","production_frozen","thresholds_frozen","failure_only","real_localization_closed","downstream_firewall"),passed=c(nrow(binding)==6L,identical(x,y),identical(sx,sy),all(x$finite_H0==x$H0_MST_edges&x$H0_max_death_error<=1e-10)&&all(x$maximum_H1_persistence[positive]>=.2)&&x$maximum_H1_persistence[x$fixture=="gaussian_negative"]<=.5,all(x$fundamental_found[positive]&x$fundamental_localized[positive]),!any(x$edge_shortest_found[positive]),!all(x$row_order_invariant),nrow(impl)==3L,!contract$production_rerun_authorized,!contract$threshold_change_authorized,contract$failure_closure_authorized_after_commit,!contract$real_localization_authorized,!any(contract[c("labels_authorized","outcomes_authorized","clustering_authorized","fusion_authorized","biology_authorized","manuscript_claims_authorized")])))
if(!all(v$passed))stop("MV17-D failure prefreeze failed")
items<-list("mv17d-failure-contract.csv"=contract,"mv17d-failure-source-binding.csv"=binding,"mv17d-failure-implementation-binding.csv"=impl,"mv17d-failure-validation.csv"=v);for(n in names(items))w(items[[n]],file.path(o,n))
writeLines(c("# MV17-D failure-closure prefreeze","","The successful primary and repeat are frozen without rerun or threshold change.","The closure must retain the second algorithm and row-order failures and keep real localization closed."),file.path(o,"MV17D_FAILURE_CLOSURE_PREFREEZE_2026-08-26.md"));f<-sort(list.files(o));w(data.frame(contract_id="mv17d_failure_manifest_v1",artifact=f,bytes=as.numeric(file.info(file.path(o,f))$size),sha256=vapply(file.path(o,f),h,character(1L))),file.path(o,"mv17d-failure-artifact-manifest.csv"))
