#!/usr/bin/env Rscript
options(warn=2); args<-commandArgs(trailingOnly=TRUE); if(length(args)!=4L) stop("usage: build_mv17e_failure_closure.R <original-prefreeze> <failure-prefreeze> <primary> <output>")
p<-normalizePath(args[[1]],mustWork=TRUE); f<-normalizePath(args[[2]],mustWork=TRUE); a<-normalizePath(args[[3]],mustWork=TRUE); o<-args[[4]]; if(dir.exists(o))stop("MV17-E failure closure exists");dir.create(o,recursive=TRUE)
source("R/mv08z_landscape_production.R"); source("R/mv17_h2_fixtures.R"); r<-.mv08z_read_csv;w<-.mv08z_atomic_csv;h<-.mv08z_sha256_file
c<-r(file.path(p,"mv17e-contract.csv")); x<-r(file.path(a,"mv17e-summary.csv")); bind<-r(file.path(f,"mv17e-failure-source-binding.csv")); at<-setNames(x$maximum_H2_persistence,x$fixture)
gates<-data.frame(contract_id="mv17e_qualitative_gate_v1",gate=c("sphere_H2_positive","torus_H1_H2_positive","circle_H1_positive_H2_negative","shuffled_sphere_attenuated","shuffled_torus_attenuated","shuffled_circle_H2_negative"),passed=c(at[["sphere"]]>=c$sphere_minimum_H2_persistence,x$H1_intervals[x$fixture=="torus"]>=c$torus_minimum_H1_features&&at[["torus"]]>=c$torus_minimum_H2_persistence,x$maximum_H1_persistence[x$fixture=="circle"]>=c$circle_minimum_H1_persistence&&at[["circle"]]<=c$circle_maximum_H2_persistence,at[["shuffled_sphere"]]<at[["sphere"]],at[["shuffled_torus"]]<at[["torus"]],at[["shuffled_circle"]]<=c$circle_maximum_H2_persistence))
payloads<-file.path(a,paste0(x$fixture,".rds")); independent<-vapply(seq_along(payloads),function(i){z<-readRDS(payloads[[i]]); h1<-mv17e_finite_intervals_v1(z$ripserr,1L);h2<-mv17e_finite_intervals_v1(z$ripserr,2L); nrow(h1)==x$H1_intervals[[i]]&&nrow(h2)==x$H2_intervals[[i]]&&abs((if(nrow(h2))max(h2$death-h2$birth)else 0)-x$maximum_H2_persistence[[i]])<=1e-12&&all(z$comparison$passed)},logical(1))
v<-data.frame(contract_id="mv17e_failure_closure_validation_v1",check_id=c("seven_fixtures","all_payloads_bound","scientific_repeat_exact","dual_engine_agreement","independent_summary_reconstruction","positive_controls_pass","negative_controls_fail","resource_caps","real_H2_closed","MV17F_closed","downstream_firewall"),passed=c(nrow(x)==7L,nrow(bind)==20L,all(bind$sha256[1:7]==bind$sha256[10:16]),all(x$engine_agreement),all(independent),all(gates$passed[c(1,2,4,5)]),!gates$passed[[3]]&&!gates$passed[[6]],max(x$ripserr_seconds+x$gudhi_seconds)<c$timeout_seconds,TRUE,TRUE,TRUE));if(!all(v$passed))stop("MV17-E failure closure failed")
decision<-data.frame(contract_id="mv17e_failure_decision_v1",MV17E_closed_negative=TRUE,failed_controls="circle_H2_negative;shuffled_circle_H2_negative",real_H2_authorized=FALSE,MV17F_authorized=FALSE,H0_H1_calibration_localization_continue=TRUE,labels_outcomes_clustering_fusion_claims="closed")
items<-list("mv17e-complete-summary.csv"=x,"mv17e-qualitative-gates.csv"=gates,"mv17e-source-binding.csv"=bind,"mv17e-validation.csv"=v,"mv17e-decision.csv"=decision);for(n in names(items))w(items[[n]],file.path(o,n));writeLines(c("# MV17-E H2 qualification negative closure","","Both engines agree and all payloads repeat exactly, but circle and shuffled-circle H2-negative controls fail.","Real-data H2 and MV17-F are closed under this estimand. H0/H1 calibration and localization continue."),file.path(o,"MV17E_H2_NEGATIVE_CLOSURE_2026-08-26.md"));z<-sort(list.files(o));w(data.frame(contract_id="mv17e_failure_closure_manifest_v1",artifact=z,bytes=as.numeric(file.info(file.path(o,z))$size),sha256=vapply(file.path(o,z),h,character(1L))),file.path(o,"mv17e-artifact-manifest.csv"))
