#!/usr/bin/env Rscript

options(warn=2)
for(p in c("digest","Matrix"))if(!requireNamespace(p,quietly=TRUE))stop(p," required.")
args<-commandArgs(trailingOnly=TRUE);if(length(args)!=5L)stop("usage: validate_mv07fp_panel_lock.R PREFREEZE PRIMARY_CACHE ADDED_CACHE EVIDENCE OUTPUT")
prefreeze<-args[[1]];primary_cache<-args[[2]];added_cache<-args[[3]];evidence<-args[[4]];output<-args[[5]]
source("R/toy_baseline.R");source("R/dual_view_topology.R");source("R/mv03_pilot.R");source("R/mv05_resource_safe_execution.R")
sha<-function(p)digest::digest(file=p,algo="sha256",serialize=FALSE);readp<-function(n)read.csv(file.path(evidence,n),stringsAsFactors=FALSE,check.names=FALSE)
manifest<-read.csv(file.path(prefreeze,"mv07fp-cache-manifest.csv"),stringsAsFactors=FALSE,check.names=FALSE);paths<-ifelse(manifest$source_tier=="primary90",file.path(primary_cache,manifest$private_cache_file),file.path(added_cache,manifest$private_cache_file))
base<-NULL;presence<-NULL;variances<-NULL;union_features<-character();cache_ok<-logical(nrow(manifest))
for(i in seq_len(nrow(manifest))){record<-readRDS(paths[i]);valid<-tryCatch({mv05d0_validate_normalization_cache_record_v2(record);TRUE},error=function(e)FALSE);value<-if(valid)mv05d0_sct_matrix_from_cache_v1(record)else NULL;cache_ok[i]<-valid&&sha(paths[i])==manifest$private_cache_sha256[i]&&record$identity$sample_id==manifest$sample_id[i]&&record$identity$seed==manifest$seed[i]&&record$payload_sha256==manifest$payload_sha256[i]&&ncol(value)==384L&&all(is.finite(value@x));if(!cache_ok[i])stop("MV7-FP independent cache failure at ",i);features<-rownames(value);union_features<-union(union_features,features);if(is.null(base)){base<-features;presence<-integer(length(base));variances<-matrix(NA_real_,length(base),nrow(manifest))};matched<-match(base,features);present<-which(!is.na(matched));presence[present]<-presence[present]+1L;variances[present,i]<-.mv03_row_variance(value[matched[present],,drop=FALSE]);rm(record,value);if(i%%25L==0L)invisible(gc())}
common<-sort(base[presence==620L],method="radix");variances<-variances[match(common,base),,drop=FALSE];finite<-is.finite(variances);positive<-finite&variances>.Machine$double.eps;ranks<-apply(variances,2L,function(x)rank(-x,ties.method="min",na.last="keep"));median_rank<-apply(ranks,1L,median,na.rm=TRUE);minimum_variance<-apply(variances,1L,function(x)if(all(is.finite(x)))min(x)else NA_real_);canonical<-canonical_mv03_gene_ids(common);category<-mv03_feature_category(common)
candidate<-data.frame(feature_id=common,gene=canonical,category=category,finite_cache_count=rowSums(finite),positive_cache_count=rowSums(positive),finite_all_caches=rowSums(finite)==620L,positive_all_caches=rowSums(positive)==620L,median_variance_rank=median_rank,minimum_variance=minimum_variance,stringsAsFactors=FALSE);retained<-candidate[candidate$category=="retained_candidate"&candidate$finite_all_caches&candidate$positive_all_caches,,drop=FALSE];retained<-retained[order(retained$median_variance_rank,retained$gene,retained$feature_id,method="radix"),,drop=FALSE];before<-nrow(retained);retained<-retained[!duplicated(retained$gene),,drop=FALSE];expected<-head(retained,500L);expected$panel_order<-seq_len(nrow(expected));panel_sha<-digest::digest(expected[c("panel_order","feature_id","gene")],algo="sha256",serialize=TRUE)
summary<-readp("mv07fp-source-summary.csv");eligibility<-readp("mv07fp-eligibility.csv");panel<-readp("mv07fp-panel.csv");stability<-readp("mv07fp-seed-stability.csv");comparison<-readp("mv07fp-panel-comparison.csv");decision<-readp("mv07fp-decision.csv");resource<-readp("mv07fp-resource.csv");artifacts<-readp("mv07fp-artifact-manifest.csv")
summary_ok<-summary$records_verified==620L&&summary$biological_samples==124L&&summary$union_features==length(union_features)&&summary$common_features==length(common)
eligibility_ok<-eligibility$eligible_features_before_canonical_deduplication==before&&eligibility$eligible_unique_canonical_genes==nrow(retained)&&eligibility$selected_panel_size==500L
panel_ok<-nrow(panel)==500L&&identical(panel$feature_id,expected$feature_id)&&identical(panel$gene,expected$gene)&&unique(panel$panel_sha256)==panel_sha&&all(panel$finite_cache_count==620L)&&all(panel$positive_cache_count==620L)
seed_ok<-all(stability$cache_count==124L)&&identical(as.integer(stability$seed),20260805:20260809)
comparison_ok<-comparison$new_panel_sha256==panel_sha&&comparison$feature_overlap==length(intersect(panel$feature_id,read.csv("docs/audits/mv06c-global-core-evidence/mv06c-panel.csv",stringsAsFactors=FALSE)$feature_id))
decision_ok<-decision$decision=="lock_exact_124_panel_and_authorize_MV7G_prefreeze"&&decision$panel_sha256==panel_sha&&sum(decision[c("pca_jobs","ph_jobs","landscape_jobs","label_jobs","outcome_jobs")])==0
det<-file.path(evidence,artifacts$file);artifact_ok<-all(file.exists(det))&&all(as.numeric(file.info(det)$size)==artifacts$bytes)&&all(vapply(det,sha,character(1))==artifacts$sha256)
checks<-data.frame(contract_id="mv07fp_independent_validation_v1",category=c("cache_axis","cache_content","source_summary","eligibility","ordered_panel","seed_stability","panel_comparison","decision_resource","artifact_manifest"),passed=c(nrow(manifest)==620L&&length(unique(manifest$sample_id))==124L,all(cache_ok),summary_ok,eligibility_ok,panel_ok,seed_ok,comparison_ok,decision_ok&&resource$elapsed_cap_pass&&resource$rss_cap_pass,artifact_ok),detail=c("620 records","620 payloads","union and intersection","eligible core","exact 500","five seeds","old versus new","MV7-G only","seven outputs"),stringsAsFactors=FALSE)
if(!all(checks$passed))stop("MV7-FP validation failed: ",paste(checks$category[!checks$passed],collapse=", "))
write.csv(checks,output,row.names=FALSE,na="");message("MV7-FP independent validation: 9/9 pass")
