#!/usr/bin/env Rscript

options(warn=2);if(!requireNamespace("digest",quietly=TRUE))stop("digest required.");source("R/mv07fp_panel_lock.R")
args<-commandArgs(trailingOnly=TRUE);if(length(args)!=6L)stop("usage: validate_mv07fp_panel_prefreeze.R DIR PRIMARY_LEDGER PRIMARY_CACHE ADDED_CACHE EXPECTED_HEAD OUTPUT")
dir<-args[[1]];ledger_path<-args[[2]];primary_cache<-args[[3]];added_cache<-args[[4]];head<-args[[5]];output<-args[[6]]
sha<-function(p)digest::digest(file=p,algo="sha256",serialize=FALSE);readc<-function(n)read.csv(file.path(dir,n),stringsAsFactors=FALSE,check.names=FALSE)
manifest<-readc("mv07fp-cache-manifest.csv");freeze<-readc("mv07fp-source-freeze.csv");contract<-readc("mv07fp-contract.csv");caps<-readc("mv07fp-resource-caps.csv");acceptance<-readc("mv07fp-acceptance.csv");decision<-readc("mv07fp-decision.csv")
paths<-ifelse(manifest$source_tier=="primary90",file.path(primary_cache,manifest$private_cache_file),file.path(added_cache,manifest$private_cache_file))
source_paths<-freeze$artifact_locator;source_paths[freeze$private_source]<-ledger_path
checks<-data.frame(contract_id="mv07fp_prefreeze_validation_v1",category=c("source_freeze","cache_axis","cache_identity","contract","resource_caps","acceptance","decision"),passed=c(nrow(freeze)==15L&&all(freeze$accepted_head==head)&&all(vapply(seq_len(nrow(freeze)),function(i)file.exists(source_paths[i])&&sha(source_paths[i])==freeze$sha256[i],logical(1))),nrow(manifest)==620L&&length(unique(manifest$sample_id))==124L&&all(table(manifest$seed)==124L),all(file.exists(paths))&&all(vapply(paths,sha,character(1))==manifest$private_cache_sha256)&&all(as.numeric(file.info(paths)$size)==manifest$private_cache_bytes),nrow(contract)==1L&&contract$panel_jobs_authorized==1L&&contract$pca_jobs_authorized==0L&&contract$ph_jobs_authorized==0L,nrow(caps)==1L&&caps$elapsed_cap_seconds==2700&&caps$rss_cap_bytes==8*1024^3,nrow(acceptance)==7L&&all(.mv07fp_truth(acceptance$passed)),nrow(decision)==1L&&decision$decision=="authorize_one_streamed_620_cache_panel_lock"&&!any(.mv07fp_truth(decision[c("pca_authorized","ph_authorized","landscape_authorized","labels_authorized","outcomes_authorized")]))) ,detail=c("15 exact sources","124 by five axis","620 hashes and sizes","panel only","2700s 8GiB","7 of 7","one inventory"),stringsAsFactors=FALSE)
if(!all(checks$passed))stop("MV7-FP prefreeze validation failed: ",paste(checks$category[!checks$passed],collapse=", "))
write.csv(checks,output,row.names=FALSE,na="");message("MV7-FP prefreeze validation: 7/7 pass")
